import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
// import 'package:firebase_core/firebase_core.dart';
// import 'firebase_options.dart'; // This will be generated by flutterfire configure

import 'app.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase (Commented out until google-services.json is available)
  // await Firebase.initializeApp(
  //   options: DefaultFirebaseOptions.currentPlatform,
  // );

  // Initialize Local Storage (Hive/SecureStorage) if needed here

  runApp(
    const ProviderScope(
      child: AiAssistantApp(),
    ),
  );
}
