import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
// import 'package:firebase_core/firebase_core.dart';
// import 'firebase_options.dart'; // This will be generated by flutterfire configure

import 'app.dart';
import 'presentation/providers/settings_provider.dart';
import 'presentation/providers/assistant_provider.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase (Commented out until google-services.json is available)
  // await Firebase.initializeApp(
  //   options: DefaultFirebaseOptions.currentPlatform,
  // );

  // Initialize Local Storage (Hive/SecureStorage) if needed here

  runApp(
    const ProviderScope(
      child: AppStartup(),
    ),
  );
}

class AppStartup extends ConsumerStatefulWidget {
  const AppStartup({super.key});

  @override
  ConsumerState<AppStartup> createState() => _AppStartupState();
}

class _AppStartupState extends ConsumerState<AppStartup> {
  @override
  void initState() {
    super.initState();
    _loadSettings();
  }

  Future<void> _loadSettings() async {
    // Load keys from secure storage on app start
    await ref.read(settingsServiceProvider).loadKeys(ref);

    // Initialize Notification Service based on settings
    _updateNotificationService();
  }

  void _updateNotificationService() {
    final enabled = ref.read(notificationEnabledProvider);
    final service = ref.read(notificationServiceProvider);

    if (enabled) {
      service.startListening();
    } else {
      service.stopListening();
    }
  }

  @override
  Widget build(BuildContext context) {
    // Listen for changes in notification settings to toggle service
    ref.listen(notificationEnabledProvider, (previous, next) {
      if (next != previous) {
        _updateNotificationService();
      }
    });

    return const AiAssistantApp();
  }
}
